--
-- Contenu de la table `qualification`
--

INSERT INTO `qualification` (`idQualification`, `libelleQualification`) VALUES
(1, 'A.M.P.  pour adultes'),
(2, 'Agent administratif principal'),
(3, 'Agent de service intérieur'),
(4, 'Agent d\'entretien'),
(5, 'Agent technique'),
(6, 'Agent technique supérieur'),
(7, 'Aide médico-psychologique'),
(8, 'Animateur'),
(9, 'Animateur socio-éducatif'),
(10, 'Assistante sociale spécialisée enfance inadaptée'),
(11, 'Cadre classe 1 niveau 1'),
(12, 'Cadre classe 2 niveau 2'),
(13, 'Cadre classe 2 niveau 3'),
(14, 'Cadre Hors classe - Directeur général'),
(15, 'Cadre technicien de niveau 1'),
(16, 'Psychologue - Cadre technicien de niveau 3'),
(17, 'Candidat Educateur spécialisé'),
(18, 'Conseillère en économie familiale et sociale'),
(19, 'Cuisinier qualifié'),
(20, 'Educateur scolaire'),
(21, 'Educateur scolaire spécialisé'),
(22, 'Educateur spécialisé'),
(23, 'Educateur sportif niveau 4'),
(24, 'Educateur technique'),
(25, 'Educateur technique spécialisé'),
(26, 'Infirmier'),
(27, 'Instituteur'),
(28, 'Maître ou Maîtresse de maison'),
(29, 'Médecin généraliste'),
(30, 'Médecin pédiatre'),
(31, 'Moniteur adjoint d\'animation et/ou d\'activités'),
(32, 'Moniteur d\'atelier de 2eme classe'),
(33, 'Moniteur éducateur'),
(34, 'Monitrice d\'enseignement ménager'),
(35, 'Orthophoniste'),
(36, 'Ouvrier Qualifié'),
(37, 'Professeur d\'éducation physique et sportive'),
(38, 'Professeur des écoles'),
(39, 'Psychiatre direction'),
(40, 'Psychiatre ou neuro-psychiatre'),
(41, 'Psychomotricien'),
(42, 'Secrétaire médicale'),
(43, 'Surveillant de nuit'),
(44, 'Surveillant de nuit qualifié'),
(45, 'Technicien qualifié'),
(46, 'Technicien supérieur');